# Changes here will be overwritten by Copier
_commit: 973c39c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: true
email: CSPOpenSource@point72.com
github: Point72
project_description: A csp adapter for slack
project_name: csp adapter slack
python_version_primary: '3.11'
team: Point72, L.P.
